config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = ([
    path('admin/', admin.site.urls),
    path('', include('reservation.urls', namespace='reservation')),
    path('users/', include('users.urls'), name='users'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

reservation/urls.py
from django.urls import path
from reservation.apps import ReservationConfig
from reservation.views import TableTemplateView, TableListView, TableDetailView, TableCreateView, TableDeleteView, \
    TableUpdateView, AboutRestoTemplateView, ReservationCreateView, ContactsTemplateView

app_name = ReservationConfig.name

urlpatterns = [
    path('', TableTemplateView.as_view(), name='base'),
    path('table_list/', TableListView.as_view(), name='table_list'),
    path('reservation/', ReservationCreateView.as_view(), name='reservation'),
    path('contacts/', ContactsTemplateView.as_view(), name='contacts'),
    path('about_resto/', AboutRestoTemplateView.as_view(), name='about_resto'),
    path('create/', TableCreateView.as_view(), name='create'),
    path('<int:pk>/', TableDetailView.as_view(), name='view'),
    path('<int:pk>/update/', TableUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete/', TableDeleteView.as_view(), name='delete'),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, reset_password, ProfileView, UserLoginView

app_name = UsersConfig.name


urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email_confirm/<str:token>/', email_verification, name='email_confirm'),
    path("profile/", ProfileView.as_view(), name="profile"),
    path('reset_password/', reset_password, name='reset_password'),
]

reservation/models.py
from django.core.exceptions import ValidationError
from django.db import models
from users.models import User

NULLABLE = {"blank": True, "null": True}


class Table(models.Model):
    table = models.IntegerField(primary_key=True, help_text='Укажите номер стола', verbose_name='Номер стола')
    seats = models.IntegerField(help_text='Количество мест', verbose_name='Количество мест')
    min_people = models.IntegerField(help_text='Введите минимальное количество людей', verbose_name='Минимум человек',
                                     **NULLABLE)
    max_people = models.IntegerField(help_text='Введите максимальное количество людей', verbose_name='Максимум человек',
                                     **NULLABLE)
    image = models.ImageField(upload_to='reservation/', verbose_name='Изображение', **NULLABLE)

    class Meta:
        verbose_name = 'Стол'
        verbose_name_plural = 'Столы'

    def __str__(self):
        return f'{self.table}'


class Reservation(models.Model):
    first_name = models.CharField(max_length=200, help_text='Укажите Имя', verbose_name='Имя', **NULLABLE)
    last_name = models.CharField(max_length=200, help_text='Укажите Фамилию', verbose_name='Фамилия', **NULLABLE)
    email = models.EmailField(verbose_name='Ваш email', **NULLABLE)
    table = models.ForeignKey(Table, on_delete=models.CASCADE, verbose_name='Номер стола', **NULLABLE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE)
    phone = models.CharField(max_length=35, verbose_name="Телефон", **NULLABLE, help_text="Введите номер телефона")
    time_reserved = models.TimeField(help_text='Укажите время', verbose_name='Время бронирования', **NULLABLE)
    date_reserved = models.DateField(help_text='Укажите дату', verbose_name='Дата бронирования', **NULLABLE)
    is_booked = models.BooleanField(default=False, verbose_name='Признак брони')

    class Meta:
        verbose_name = 'Бронирование'
        verbose_name_plural = 'Бронирование'

        # unique_together = ('time_reserved', 'date_reserved','table')
        constraints = [
            models.UniqueConstraint(fields=['time_reserved', 'date_reserved', 'table'], name='name of constraint')
        ]

    def __str__(self):
        return f'Стол номер {self.table}, клиент {self.first_name} {self.last_name}, {self.owner}'


# class ReservedConstraint(models.UniqueConstraint):
#     def validate(self, model, instance, exclude=None, using="default"):
#         super().validate(model, instance, exclude=exclude, using=using)
#
#         res = model.objects.filter(
#             time_reserved=instance.time_reserved,
#             date_reserved=instance.date_reserved,
#             table=instance.table,
#             is_booked=True
#         ).exists()
#
#         if res:
#             raise ValidationError('Такое бронирование уже существует')
#

reservation/forms.py
from django import forms

from common.view import StyleFormMixin
from reservation.models import Table, Reservation
from users.models import User


class TableForms(StyleFormMixin, forms.ModelForm):
    def __init__(self, *args, request=None, **kwargs):
        super().__init__(*args, **kwargs)
        if request is not None:
            self.fields['recipients'].queryset = User.objects.filter(owner=request.user)
            self.fields['table'].queryset = Table.objects.filter(owner=request.user)

    class Meta:
        model = Table
        fields = ('table', 'seats', 'image')


class ReservationForm(StyleFormMixin, forms.ModelForm):
    # time_reserved = forms.CharField(
    #     widget=forms.TextInput(attrs={'class': 'input-group'}))
    # date_reserved = forms.DateField(widget=forms.TextInput(
    #     attrs={'placeholder': 'yyyy-mm-dd',
    #            'id': 'datepicker'}), required=True,)

    class Meta:
        model = Reservation
        fields = ['first_name', 'last_name',
                  'table',
                  'email', 'phone', 'time_reserved',
                  'date_reserved']


class ReservationUpdateForm(StyleFormMixin, forms.ModelForm):
    # time_reserved = forms.CharField(
    #     widget=forms.TextInput(attrs={'id': 'timepicker',
    #                                   'class': 'input-group'}))
    # date_reserved = forms.DateField(widget=forms.TextInput(
    #     attrs={'placeholder': 'yyyy-mm-dd',
    #            'id': 'datepicker'}), required=True,)

    class Meta:
        model = Reservation
        fields = ['first_name',
                  'email', 'time_reserved',
                  'date_reserved']

reservation/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, CreateView, ListView, DetailView, UpdateView, DeleteView

from reservation.forms import TableForms, ReservationForm, ReservationUpdateForm
from reservation.models import Table, Reservation
from reservation.users_cases import save_feedback


class TableTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'reservation/home.html'


class TableCreateView(LoginRequiredMixin, CreateView):
    model = Table
    form_class = TableForms
    success_url = reverse_lazy('reservation:table_list')

    def form_valid(self, form):
        message = form.save()
        message.owner = self.request.user
        message.save()
        return super().form_valid(form)


class TableListView(LoginRequiredMixin, ListView):
    model = Table


class TableDetailView(LoginRequiredMixin, DetailView):
    model = Table


class TableUpdateView(LoginRequiredMixin, UpdateView):
    model = Table
    form_class = TableForms
    success_url = reverse_lazy('reservation:table_list')


class TableDeleteView(LoginRequiredMixin, DeleteView):
    model = Table
    success_url = reverse_lazy('reservation:table_list')


class ReservationListView(ListView):
    model = Reservation
    title = 'Бронирование'

    # def get_queryset(self, args, **kwargs):
    #     """
    #     Отображает только доступные к брони столики.
    #     """
    #     queryset = super().get_queryset(args, **kwargs)
    #     queryset = queryset.filter(is_booked=False)
    #     return queryset


class ReservationCreateView(LoginRequiredMixin, CreateView):
    model = Reservation
    template_name = "reservation/reservation.html"
    form_class = ReservationForm
    success_url = reverse_lazy('reservation:reservation')

    def form_valid(self, form):
        new_reservate = form.save(commit=False)
        new_reservate.owner = self.request.user
        new_reservate.save()
        super().form_valid(form)
        return redirect('/')


class AboutRestoTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'reservation/about_restaurant.html'


# class UpdateReservation(LoginRequiredMixin, UpdateView):
#     """Admin user updates all the reservation."""
#     form_class = ReservationUpdateForm
#     template_name = "super/update_reserve.html"
#     model = Reservation
#
#     def get_object(self, *args, **kwargs):
#         obj = get_object_or_404(Reservation, pk=self.kwargs['pk'])
#         return obj
#
#     def form_valid(self, form):
#         val = form.cleaned_data['status']
#         form.save()
#         messages.success(
#             self.request, "you have successfully updated the reservation")
#         if val == "confirmed":
#             return redirect('orders:reservation_status', pk=self.kwargs['pk'])
#         return redirect('/dashboard')


class ContactsTemplateView(TemplateView):
    template_name = "reservation/contacts.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Контакты"
        return context

    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            save_feedback(
                name=request.POST.get('name'),
                phone=request.POST.get('phone'),
                message=request.POST.get('message')
            )
        return HttpResponseRedirect(reverse('reservation:contacts'))

reservation/templates/reservation/base.html
<!doctype html>

{% include 'reservation/main_menu.html' %}
{% load static %}
<html lang="ru" data-bs-theme="auto">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

</head>
<body>
<div class="nav-scroller py-1 mb-3 border-bottom">
    <nav class="nav nav-underline justify-content-between">
        {% if user.is_superuser %}
        <a class="nav-item nav-link link-body-emphasis" href="{% url 'reservation:create' %}">Добавить стол</a>
        {% endif %}
        <a class="nav-item nav-link link-body-emphasis" href="{% url 'reservation:base' %}">Главная страница</a>
        <a class="nav-item nav-link link-body-emphasis" href="{% url 'reservation:table_list' %}">Список столов</a>
        <a href="{% url 'users:profile' %}" class="nav-item nav-link link-body-emphasis">Личный кабинет</a>
    </nav>
</div>


<div class="container">
    {% block content %}
    {% endblock %}
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                Fish and Meat
                <small class="d-block mb-3 text-muted">&copy; 2024</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки pass</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты pass</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты pass</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения pass</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем pass</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                    <li><a class="text-muted" href="{% url 'reservation:about_resto' %}">О ресторане</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

</body>
</html>

reservation/templates/reservation/contacts.html
{% extends 'reservation/base.html' %}
{% block content %}
{% load my_tags %}
{% load static %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>Россия</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>244603496011</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Абаканская ул. 99, Абакан</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Текст сообщения" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-secondary fw-bold border-white bg-black">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

reservation/templates/reservation/home.html
<!doctype html>

{% include 'reservation/main_menu.html' %}
{% load static %}

<html lang="ru" data-bs-theme="auto">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">


<div class="d-flex h-100 text-center p-5 mx-auto flex-column">
    <div class="card-header">
        <main class="card-header">
            <h1>Приветствуем на главной странице ресторана</h1>
            <h1>Рады вашему визиту на сайте ресторана "Рыба и Мясо"</h1>

        </main>
    </div>
    <div class="d-flex h-100 text-center p-5 mx-auto flex-column">
        <div class="card-header">
            <h1> Описание ресторана</h1>
            <p class="lead">«Рыба и Мясо» специализируется на трех кухнях: японская, итальянская, русская. Отсюда и
                название предприятия, поскольку предоставляется разнообразие кухонь.


                Обслуживание в ресторане осуществляется официантами. Меню и его обложка оформлены типографическим
                способом на пластиковых листах. Листы меню соединены коричневыми ленточками. Блюда и напитки имеют
                живописание и фотографии. В меню указано наименование блюда (напитка), указана цен и выход в граммах (в
                миллилитрах). Количество меню составляет 30 штук. В резерве имеется еще 10 штук. Карты вин в ресторане
                нет, весь ассортимент напитков предложен в меню. Тарелки используются в ресторане полу-фарфоровая;
                приборы из нержавеющей стали, посуда из стекла (бокалы, стаканы, фужеры). Скатерти и салфетки
                используются льняные, скатерти темно коричневого цвета, салфетки светло-коричневого цвета. Столы в
                предприятии деревянные, стулья тоже деревянные. В кальян-баре имеются диваны коричневого цвета. Вся
                мебель в ресторане повышенной комфортности и соответствует интерьеру, общему стилю предприятия. Интерьер
                зала выдержан в коричнево-бежевых тонах. При отделке зала были использованы материалы из дерева. Для
                оформления залов и помещений для потребителей используются изысканные и оригинальные декоративные
                элементы (светильники, картины)

                Рекламная вывеска ресторана красочная, имеет логотип ресторана, адрес, телефон и режим работы
                предприятия, а также имеет подсветку. Предприятие состоит из следующих помещений: обеденный зал с барной
                стойкой, кальян-бар, производственный цех, подсобное помещение, моечная столовой посуды, гардеробная для
                сотрудников, кабинет администратора, склад хозяйственного инвентаря, туалет, коридор. Выделен участок по
                обработке полуфабрикатов, где установлены моечные ванны, производственные столы и низкотемпературное
                холодильное оборудование. Водоснабжение горячее и холодное. За барной стойкой оборудован участок по
                изготовлению кулинарных изделий японской кухни. Для создания оптимального микроклимата в торговом зале
                ресторана существует система кондиционирования воздуха с автоматическим поддержанием оптимальных
                параметров температуры и влажности. Предприятие имеет огнетушители для тушения пожара. Имеются средства
                от поражения электрическим током и телефонная связь. Персонал ресторана носит форменную одежду – черную
                блузку, черные брюки, коричневый фартук. На предприятии разработано штатное расписание. В нем
                фиксируются должностные оклады по структурным подразделениям, как для административно-управленческого
                персонала, так и для служащих и рабочих. В штатном расписании устанавливаются должностные оклады,
                надбавка к ним, количество сотрудников данной должности, определяется фонд заработной платы структурных
                подразделений.
            </p>
            <h1> Перечень предоставляемых услуг</h1>
            <p class="lead">Ресторан «Рыба и Мясо» оказывает следующие услуги:

                −Услуга питания

                −Услуга по изготовлению и реализации кулинарной продукции и

                кондитерских изделий

                −Услуга по организации потребления и обслуживания

                −Услуга по организации досуга (организация музыкального обслуживания, предоставление газет, журналов)

                −Прочие услуги (упаковка блюд и изделий; предоставление средств связи; вызов такси)

                Ресторан предоставляет организацию бизнес - ланч с 12.00 до 16.00. А также дополнительные услуги: заказ
                и доставка потребителям кулинарных и кондитерских изделий на дом, бронирование мест в зале, отпуск
                изделий японской кухни и пиццы на вынос.
            </p>

        </div>
        <p class="lead">
                <a href="{% url 'reservation:table_list' %}"
                   class="btn btn-lg btn-secondary fw-bold border-white bg-black">Зарезервировать столик</a>
            </p>
    </div>

    <div class="container">
        {% block content %}
        {% endblock %}
        <footer class="pt-4 my-md-5 pt-md-5 border-top">
            <div class="row">
                <div class="col-12 col-md">
                    Fashion Family
                    <small class="d-block mb-3 text-muted">&copy; 2023</small>
                </div>
                <div class="col-6 col-md">
                    <h5>Категории</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Рассылки pass</a></li>
                        <li><a class="text-muted" href="#">Телеграм боты pass</a></li>
                        <li><a class="text-muted" href="#">Полезные утилиты pass </a></li>
                        <li><a class="text-muted" href="#">Веб-приложения pass</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>Дополнительно</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Мы пишем pass</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>О нас</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                        <li><a class="text-muted" href="{% url 'reservation:about_resto' %}">О ресторане</a></li>
                    </ul>
                </div>
            </div>
        </footer>
    </div>

</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>


</html>

reservation/templates/reservation/main_menu.html
{% block content %}
<header data-bs-theme="dark">
    <div class="collapse text-bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-4 offset-md-10 py-4">
                    <ul class="list-unstyled">
                        {% if user.is_superuser %}
                        <li><a class="nav-item nav-link link-body-emphasis"
                               href="{% url 'admin:index' %}">Админ-панель</a></li>
                        {% endif %}
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'reservation:base' %}" class="text-white">Главная страница</a></li>
                        <li><a href="{% url 'reservation:table_list' %}" class="text-white">Список столов</a></li>
                        <li><a href="{% url 'users:profile' %}" class="text-white">Профиль</a></li>
                        <li><a href="{% url 'reservation:about_resto' %}" class="text-white">О ресторане</a></li>
                        <li><a href="{% url 'users:logout' %}" class="text-white">Выход</a></li>
                        {% else %}
                        <li><a href="{% url 'users:login' %}" class="text-white">Вход</a>/<a
                                href="{% url 'users:register' %}" class="text-white">Регистрация</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <a href="/" class="navbar-brand d-flex align-items-center">
                <strong>Рыба и мясо</strong>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>
{% endblock %}

reservation/templates/reservation/reservation.html
{% extends 'reservation/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <form class="row" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="card">
                    <div class="card-body">
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-lg btn-secondary fw-bold border-white bg-black">Забронировать стол</button>
<!--                    <input type="owner"  class="form-control" id="owner" name="owner">-->
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

reservation/templates/reservation/table_confirm_delete.html
{% extends 'reservation/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p>Хотите удалить стол? {{ object.title }}?</p>
                        <button type="submit" class="btn btn-success">Удалить</button>
                        <a class="btn btn-primary" href="{% url 'reservation:table_list' %}" role="button">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

reservation/templates/reservation/table_detail.html
{% extends 'reservation/base.html' %}
{% block content %}
{% load my_tags %}

<div class="container">
    <div class="row text-center">
        <div class="col-9">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h2 class="my-0 fw-normal">Стол номер {{ object.table }}</h2>
                    <h3 class="my-0 fw-normal">На {{ object.seats }} персоны</h3>
                    {% if object.image %}
                    <img class="card-img-top" src="{{ object.image | media_filter  }}">
                    {% endif %}
                </div>
                <div class="card-body">
                    <a class="btn btn-lg btn-secondary fw-bold border-white bg-black"
                       href="{% url 'reservation:reservation' %}" role="button">Зарезервировать</a>
                    {% if user == object.owner or user.is_superuser %}
                    <a class="btn btn-primary" href="{% url 'reservation:edit' object.pk %}" role="button">Изменить</a>
                    <a class="btn btn-primary" href="{% url 'reservation:delete' object.pk %}" role="button">Удалить</a>
                    {% endif %}
                    <a class="btn btn-lg btn-secondary fw-bold border-white bg-black"
                       href="{% url 'reservation:table_list' %}" role="button">Назад</a>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

reservation/templates/reservation/table_form.html
{% extends 'reservation/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <form class="row" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="card">
                    <div class="card-body">
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary mt-3">
                        {% if object %}
                            Изменить стол
                        {% else %}
                            Добавить стол
                        {% endif %}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

reservation/templates/reservation/table_list.html
{% extends 'reservation/base.html' %}
{% block content %}
<div class="pricing-header p-3 pb-md-4 mx-auto text-center">
    <h1 class="display-4 fw-normal text-body-emphasis">Все столы</h1>
    <h3>
    </h3>
</div>

<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    {% for table in object_list %}

    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h2 class="my-0 fw-normal">Стол номер {{ table.table }}</h2>
                <h3 class="my-0 fw-normal">На {{ table.seats }} персоны</h3>

            </div>
            <div class="card-body">
                <a class="btn btn-lg btn-secondary fw-bold border-white bg-black" href="{% url 'reservation:view' table.pk %}" role="button">Просмотреть</a>
            </div>
        </div>
    </div>

    {% endfor %}
</div>
{% endblock %}